services:
  postgres:
    image: postgres:16-alpine
    container_name: garmin_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: garmin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432" # <-- El puerto externo ahora es el 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: garmin_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@garmin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
